DROP TABLE IF EXISTS path CASCADE;
DROP TABLE IF EXISTS place CASCADE;

CREATE TABLE place (
   id BIGINT NOT NULL AUTO_INCREMENT,
   name VARCHAR(100) NOT NULL,
   latitude DOUBLE PRECISION NOT NULL,
   longitude DOUBLE PRECISION NOT NULL,
   PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE path (
   id BIGINT NOT NULL AUTO_INCREMENT,
   from_place_id BIGINT NOT NULL,
   to_place_id BIGINT NOT NULL,
   distance DOUBLE PRECISION NOT NULL,
   PRIMARY KEY (id)
) ENGINE=InnoDB;

ALTER TABLE place ADD CONSTRAINT place_position UNIQUE (latitude, longitude);
ALTER TABLE path ADD CONSTRAINT path_uq UNIQUE (from_place_id, to_place_id);
ALTER TABLE path ADD CONSTRAINT path_fk_from_place FOREIGN KEY (from_place_id) REFERENCES place (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE path ADD CONSTRAINT path_fk_to_place FOREIGN KEY (to_place_id) REFERENCES place (id) ON DELETE CASCADE ON UPDATE CASCADE;